# Defines the "memory" passed between agents

from typing import TypedDict, Annotated, List, Optional
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field

# Pydantic Models for Structured Outputs

class SearchQuery(BaseModel):
    """Structured output for the researcher to generate search queries."""
    queries: List[str] = Field(description="List of search queries to execute")

class ScrapedDocument(BaseModel):
    """Represents a single scraped webpage."""
    url: str
    title: str
    content: str
    snippet: Optional[str] = None

class FinalReport(BaseModel):
    """The final structured report generated by the writer."""
    title: str
    executive_summary: str
    sections: List[dict] # e.g., [{"heading": "...", "content": "..."}]
    sources: List[str]

# LangGraph State Definition

class ResearchState(TypedDict):
    """
    The core state of our Multi-Agent Graph.
    This dictionary is passed between every node (agent) in the graph.
    """
    # Messages & Conversation History
    messages: Annotated[list, add_messages]
    
    # User Input
    user_topic: str 
    target_audience: Optional[str]
    
    # Research Data (Researcher Node)
    search_queries: List[str]
    scraped_documents: List[dict] 
    rag_context: Optional[str] 
    
    # Drafting & Reviewing (Writer & Reviewer Nodes)
    draft_report: Optional[str]
    academic_context: Optional[str]  # Academic papers from OpenAlex
    
    # 🔄 UPDATED: Renamed from review_feedback to match the reviewer agent
    reviewer_feedback: Optional[str]      
    
    # 🆕 ADDED: The specific fields for the Reviewer loop we discussed
    is_approved_by_reviewer: bool         
    revision_count: int                   
    MAX_REVISIONS: int                    
    
    
    # Human in the Loop & Export (Streamlit UI & Export Node)
    is_approved_by_human: bool
    
    # FIXED: Removed the duplicate 'export_format' and 'file_path' definitions
    export_format: str                    # 'pdf', 'docx', or 'md'
    file_path: Optional[str]              # Path to the exported file (Optional because it doesn't exist until the end)